### ISSUE TITLE
ess.krbk.dev marche pas chez moi

### ISSUE THREAD

**Issue by alexis-rarchaert** [justekoro/essence#4]
le site charge en boucle, et pas d'erreur dans le F12 ;(

**Comment by justekoro** [comment]
yep ça me fait la même, je pense que c'est un problème de performances de ma machine... je migre le site dans la semaine.

**Comment by justekoro** [comment]
hello, des nouvelles ? @Jokay03J a réussi à fix ça normalement

**Comment by justekoro** [comment]
aucune nouvelle, je close... n'hésite pas à rouvrir une issue si le problème persiste
